### ISSUE TITLE
"createDataframe" function throws out error

### ISSUE THREAD

**Issue by YBKassim** [Photosynq/PhotosynQ-R#3]
My attempt to use the above function gives the error below:

Error in as.environment(where) : using 'as.environment(NULL)' is defunct

**Comment by SeBassTian23** [comment]
Hi @KASSIM18 
could you tell me which project you were working with? That will make the trouble shooting so much easier.

Thanks

**Comment by SeBassTian23** [comment]
The issue should be fixed now 1a2db32facb4af33077be6f7e388e6d11f37a25e.

**Comment by SeBassTian23** [comment]
Please install the latest release `0.2.1`.

**Comment by YBKassim** [comment]
Hi Sebastian

Sorry for my late response. I took data with MultiSpeq on peanut. Initially
I could extract my data using the R package, but some few weeks later it
throws out that error after I have taken a new data and wanted to extract
it.
But then since you said you have fixed it, I will try again.

Warm regards,
Kassim.
https://orcid.org/0000-0002-3994-5066
Creative data analysis will help the discovery of new plant traits and
approaches to plant improvement.....###CSSA
